### ISSUE TITLE
Values for HARVEST table ? 

### ISSUE THREAD

**Issue by gkowalski** [PCORnet-DRN-OC/PCORnet-Diagnostic-Query#1]
The CDMv3 spec says the following for the values within the HARVEST table :

NETWORKID - This identifier is assigned by DSSNI operations
NETWORK_NAME - Descriptive name of the network
DATAMARTID - This identifier is assigned by DSSNI operations
DATAMART_NAME - Descriptive name of the datamart

Where do we get the values for these ?

**Comment by rusincovitch** [comment]
Hi @gkowalski: the harvest reference table is a living document on iMeetCentral at [https://pcornet.imeetcentral.com/p/aQAAAAACl2-K](https://pcornet.imeetcentral.com/p/aQAAAAACl2-K)

**Comment by rusincovitch** [comment]
Good morning, and I just wanted to check in. 

I'm going to close this issue out, but please let me know if you have any further questions!
